name: Daily RevOps Pipeline

on:
  schedule:
    - cron: '0 6 * * *'  # runs every day at 6am UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_ACCESS_TOKEN}}
        run: |
          cd revops-lead-scoring
          python pipeline.py